# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipments',
            old_name='Com_to_switch',
            new_name='Intface_to_switch',
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='Rest_IP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabinet_inner_ip',
            name='Using_condition',
            field=models.CharField(choices=[('inUsing', 'the IP is being using'), ('notUsing', 'the IP is not being using')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cabinet_outer_ip',
            name='Using_condition',
            field=models.CharField(choices=[('inUsing', 'the IP is being using'), ('notUsing', 'the IP is not being using')], max_length=10),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Inner_IP_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ControlMode.Cabinet_inner_IP'),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Outer_IP_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ControlMode.Cabinet_outer_IP'),
        ),
    ]
