# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMode', '0005_auto_20161218_1341'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cabinet_inner_ip',
            table='Global_IP_address',
        ),
        migrations.AlterModelTable(
            name='cabinet_outer_ip',
            table='Local_IP_address',
        ),
    ]
